version: '3'
services:
  daemon:
    restart: always
    hostname: daemon
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/daemon/config/:/srv/daemon/config/"
      - "/srv/daemon-data/:/srv/daemon-data/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl"
